// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {status} from '../models';

export function CancelModule():Promise<void>;

export function CheckUpdate():Promise<string>;

export function GetLang():Promise<string>;

export function GetModules():Promise<Array<config.Module>>;

export function GetStatus():Promise<status.SystemStatus>;

export function GetSubscriptionURL():Promise<string>;

export function GetSudoState():Promise<string>;

export function GetVersion():Promise<string>;

export function IsProxyRunning():Promise<boolean>;

export function LaunchUpdater():Promise<void>;

export function OpenTavern():Promise<void>;

export function RunModule(arg1:string):Promise<void>;

export function SetLang(arg1:string):Promise<void>;

export function SetSubscriptionURL(arg1:string):Promise<void>;

export function SetSudoPassword(arg1:string):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function VerifySudo(arg1:string):Promise<void>;
