// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelModule() {
  return window['go']['main']['App']['CancelModule']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function GetLang() {
  return window['go']['main']['App']['GetLang']();
}

export function GetModules() {
  return window['go']['main']['App']['GetModules']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSubscriptionURL() {
  return window['go']['main']['App']['GetSubscriptionURL']();
}

export function GetSudoState() {
  return window['go']['main']['App']['GetSudoState']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsProxyRunning() {
  return window['go']['main']['App']['IsProxyRunning']();
}

export function LaunchUpdater() {
  return window['go']['main']['App']['LaunchUpdater']();
}

export function OpenTavern() {
  return window['go']['main']['App']['OpenTavern']();
}

export function RunModule(arg1) {
  return window['go']['main']['App']['RunModule'](arg1);
}

export function SetLang(arg1) {
  return window['go']['main']['App']['SetLang'](arg1);
}

export function SetSubscriptionURL(arg1) {
  return window['go']['main']['App']['SetSubscriptionURL'](arg1);
}

export function SetSudoPassword(arg1) {
  return window['go']['main']['App']['SetSudoPassword'](arg1);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function VerifySudo(arg1) {
  return window['go']['main']['App']['VerifySudo'](arg1);
}
